---
title: "Shiny Instacart"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
  runtime: shiny
---


```{r setup, include=FALSE}


library(flexdashboard)
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(ggplot2)
library(plotly)
library(ggridges)
library(magrittr)
library(readr)
library(scales)
library(shiny)

```



```{r import_data}

# Read in the data

instacart = read_csv("./data/instacart_train_data.csv.zip") %>%
  clean_names() %>%
  distinct()

```


Column {.sidebar}
-----------------------------------------------------------------------
This `flexdashboard` with Shiny was made for Homework 6 of [Jeff Goldsmith's Data Science I class](http://jeffgoldsmith.com/DSI/homework_6.html) in the Department of Biostatistics at Columbia University. This was created by [Angel Garcia de la Garza](https://github.com/angelgar) and [Soohyun Kim](https://github.com/sk4382)

The data come from the [Instacart Dataset](http://jeffgoldsmith.com/DSI/dataset_instacart.html), which contains observations of 131,209 unique users with 1,384,617 rows in which each row is a product within an order.

```{r}

# Create lists of departments
 
departments = instacart %>%
                distinct(department) %>%
                pull()

# selectInput widget
selectInput("department_choice", label = h3("Select Department"),
            choices = departments, selected = "produce")

# set min and max hour of the day
min_hour = instacart %>% distinct(order_hour_of_day) %>% min()
max_hour = instacart %>% distinct(order_hour_of_day) %>% max()

# sliderInput widget
sliderInput("time_day", label = h3("Choose hour of the day"), min = min_hour, 
        max = max_hour, value = c(10, 17), step = 1)


```

Row {.tabset .tabset-fade } 
-----------------------------------------------------------------------

### Top 15 Most Common Items by Department

```{r}

# Barplot of most common items by department

renderPlotly({
  
  # Filter by department and time of the day and count and subset for top 15 items
  # Plot using ggplot and ggplotly
  
  barplot_product <- instacart %>%
                    filter(department == input$department_choice, 
                           order_hour_of_day <= input$time_day[2],
                           order_hour_of_day >= input$time_day[1]) %>%
                    count(product_name) %>%
                    top_n(15, n) %>%
                    mutate(product_name = fct_reorder(product_name, n)) %>%
                    ggplot(aes(x = product_name, y = n, fill = product_name)) +
                      geom_bar(stat = "identity") + 
                      theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplotly(barplot_product)

})

```


### Number of Days Since Last Order

```{r}

renderPlotly({
  
  # Filter by department and time of the day
  # Plot density of days since last order using ggplot and ggplotly
  
  histogram_last_order = instacart %>%
    filter(department == input$department_choice, 
           order_hour_of_day <= input$time_day[2],
           order_hour_of_day >= input$time_day[1]) %>%
    ggplot(aes(days_since_prior_order, ..density.., color = aisle)) + geom_freqpoly() 

ggplotly(histogram_last_order)
  
})

```

### Distribution of Number of Reordered Items 

```{r}

renderPlotly({
  
  # Filter by department and time of the day
  # Plot distribution of reordered items 
  
  boxplot_reordered = instacart %>%
    filter(department == input$department_choice, 
           order_hour_of_day <= input$time_day[2],
           order_hour_of_day >= input$time_day[1]) %>%
    group_by(aisle, product_name) %>% 
    mutate(n_reordered = sum(reordered)) %>% 
    ggplot(aes(x = aisle, y = n_reordered, fill = aisle)) +
      geom_boxplot() +
      theme(axis.text.x = element_text(angle = 90, hjust = 1))
    
ggplotly(boxplot_reordered)

})


```

